# Enabling the new cops
AllCops:
  NewCops: enable

# Adding exceptions to Rubocop's offenses
Layout/EndOfLine:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

# Unclear way of showing arrays of strings
Style/WordArray:
  Enabled: false

